// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: maxnum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMaxNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetMaxNumberRequest) Reset() {
	*x = GetMaxNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxnum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxNumberRequest) ProtoMessage() {}

func (x *GetMaxNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maxnum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxNumberRequest.ProtoReflect.Descriptor instead.
func (*GetMaxNumberRequest) Descriptor() ([]byte, []int) {
	return file_maxnum_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaxNumberRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetMaxNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetMaxNumberResponse) Reset() {
	*x = GetMaxNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxnum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxNumberResponse) ProtoMessage() {}

func (x *GetMaxNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maxnum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxNumberResponse.ProtoReflect.Descriptor instead.
func (*GetMaxNumberResponse) Descriptor() ([]byte, []int) {
	return file_maxnum_proto_rawDescGZIP(), []int{1}
}

func (x *GetMaxNumberResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_maxnum_proto protoreflect.FileDescriptor

var file_maxnum_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x69, 0x0a, 0x10, 0x4d, 0x61, 0x78,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x6f, 0x76, 0x61, 0x34, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67,
	0x6f, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maxnum_proto_rawDescOnce sync.Once
	file_maxnum_proto_rawDescData = file_maxnum_proto_rawDesc
)

func file_maxnum_proto_rawDescGZIP() []byte {
	file_maxnum_proto_rawDescOnce.Do(func() {
		file_maxnum_proto_rawDescData = protoimpl.X.CompressGZIP(file_maxnum_proto_rawDescData)
	})
	return file_maxnum_proto_rawDescData
}

var file_maxnum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_maxnum_proto_goTypes = []interface{}{
	(*GetMaxNumberRequest)(nil),  // 0: calculator.GetMaxNumberRequest
	(*GetMaxNumberResponse)(nil), // 1: calculator.GetMaxNumberResponse
}
var file_maxnum_proto_depIdxs = []int32{
	0, // 0: calculator.MaxNumberService.GetMaxNumber:input_type -> calculator.GetMaxNumberRequest
	1, // 1: calculator.MaxNumberService.GetMaxNumber:output_type -> calculator.GetMaxNumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maxnum_proto_init() }
func file_maxnum_proto_init() {
	if File_maxnum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maxnum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maxnum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maxnum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maxnum_proto_goTypes,
		DependencyIndexes: file_maxnum_proto_depIdxs,
		MessageInfos:      file_maxnum_proto_msgTypes,
	}.Build()
	File_maxnum_proto = out.File
	file_maxnum_proto_rawDesc = nil
	file_maxnum_proto_goTypes = nil
	file_maxnum_proto_depIdxs = nil
}
